import { Generator } from '../base/generator.js';
import { writeFiles } from '../../utils/fs.js';
import { join } from 'node:path';

/**
 * Expo + React Native mobile app generator.
 * Produces a minimal Expo project configured for the monorepo.
 */
export class MobileGenerator extends Generator {
  readonly name = 'mobile';

  private get mobileDir(): string {
    return join(this.config.targetDir, 'apps', 'mobile');
  }

  protected async writeFiles(): Promise<void> {
    const files: Record<string, string> = {
      'package.json': this.packageJson(),
      'tsconfig.json': this.tsconfig(),
      'app.json': this.appJson(),
      'babel.config.js': this.babelConfig(),
      'metro.config.js': this.metroConfig(),
      'expo-env.d.ts': this.expoEnvDts(),
      'src/app/_layout.tsx': this.layout(),
      'src/app/index.tsx': this.indexPage(),
      'src/lib/api-client.ts': this.apiClient(),
    };

    await writeFiles(this.mobileDir, files);
  }

  private packageJson(): string {
    const scope = this.config.packageScope;

    const pkg = {
      name: `${scope}/mobile`,
      version: '0.1.0',
      private: true,
      main: 'expo-router/entry',
      scripts: {
        dev: 'expo start',
        'dev:android': 'expo start --android',
        'dev:ios': 'expo start --ios',
        build: 'echo "No build step for Expo dev"',
        lint: 'eslint src/ --ext .ts,.tsx',
        'type-check': 'tsc --noEmit',
      },
      dependencies: {
        'expo': '~52.0.0',
        'expo-router': '~4.0.0',
        'expo-linking': '~7.0.0',
        'expo-constants': '~17.0.0',
        'expo-status-bar': '~2.0.0',
        'expo-asset': '~10.0.10',
        'expo-font': '~13.0.2',
        'expo-splash-screen': '~0.29.21',
        'react': '^18.3.0',
        'react-native': '0.76.0',
        'react-native-safe-area-context': '^4.14.0',
        'react-native-screens': '~4.4.0',
        [`${scope}/ui`]: 'workspace:*',
        [`${scope}/types`]: 'workspace:*',
        [`${scope}/utils`]: 'workspace:*',
      },
      devDependencies: {
        '@types/react': '^18.3.0',
        'typescript': '^5.6.0',
        [`${scope}/config-typescript`]: 'workspace:*',
      },
    };

    return JSON.stringify(pkg, null, 2) + '\n';
  }

  private tsconfig(): string {
    const tsconfig = {
      extends: '../../tsconfig.base.json',
      compilerOptions: {
        target: 'ESNext',
        lib: ['ESNext'],
        module: 'ESNext',
        moduleResolution: 'Bundler',
        jsx: 'react-jsx',
        strict: true,
        noEmit: true,
        paths: {
          '@/*': ['./src/*'],
        },
      },
      include: ['**/*.ts', '**/*.tsx', '.expo/types/**/*.ts', 'expo-env.d.ts'],
      exclude: ['node_modules'],
    };

    return JSON.stringify(tsconfig, null, 2) + '\n';
  }

  private appJson(): string {
    const { projectName } = this.config;
    const titleCase = projectName
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');

    const appJson = {
      expo: {
        name: titleCase,
        slug: projectName,
        version: '0.1.0',
        orientation: 'portrait',
        scheme: projectName,
        userInterfaceStyle: 'automatic',
        newArchEnabled: true,
        ios: {
          supportsTablet: true,
          bundleIdentifier: `com.${projectName.replace(/-/g, '')}.app`,
        },
        android: {
          adaptiveIcon: {
            backgroundColor: '#0f0f23',
          },
          package: `com.${projectName.replace(/-/g, '')}.app`,
        },
        plugins: ['expo-router'],
      },
    };

    return JSON.stringify(appJson, null, 2) + '\n';
  }

  private babelConfig(): string {
    return `module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
`;
  }

  private metroConfig(): string {
    return `const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

// Find the project and workspace directories
const projectRoot = __dirname;
const monorepoRoot = path.resolve(projectRoot, '../..');

const config = getDefaultConfig(projectRoot);

// 1. Watch all files within the monorepo
config.watchFolders = [monorepoRoot];

// 2. Let Metro know where to resolve packages and in what order
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(monorepoRoot, 'node_modules'),
];

module.exports = config;
`;
  }

  private expoEnvDts(): string {
    return `/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be in your git ignore list.
// This is automatically generated by Expo when you run \`expo start\`.
`;
  }

  private layout(): string {
    return `import { Stack } from 'expo-router';
import { StatusBar } from 'expo-status-bar';

export default function RootLayout() {
  return (
    <>
      <StatusBar style="light" />
      <Stack
        screenOptions={{
          headerStyle: {
            backgroundColor: '#0f0f23',
          },
          headerTintColor: '#e2e8f0',
          headerTitleStyle: {
            fontWeight: '700',
          },
          contentStyle: {
            backgroundColor: '#0f0f23',
          },
        }}
      />
    </>
  );
}
`;
  }

  private indexPage(): string {
    const { projectName } = this.config;
    const titleCase = projectName
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');

    return `import { View, Text, StyleSheet, Pressable, Linking } from 'react-native';
import { Stack } from 'expo-router';

export default function HomeScreen() {
  return (
    <>
      <Stack.Screen options={{ title: '${titleCase}' }} />
      <View style={styles.container}>
        <Text style={styles.title}>${titleCase}</Text>
        <Text style={styles.subtitle}>
          Your full-stack TypeScript monorepo is ready.
        </Text>
        <Pressable
          style={styles.button}
          onPress={() => Linking.openURL('http://localhost:3001/api/health')}
        >
          <Text style={styles.buttonText}>Check API Health →</Text>
        </Pressable>
      </View>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f0f23',
    padding: 24,
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: '#7c3aed',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#94a3b8',
    textAlign: 'center',
    marginBottom: 32,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    backgroundColor: '#7c3aed',
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 16,
  },
});
`;
  }

  private apiClient(): string {
    return `/**
 * API client for communicating with the backend from React Native.
 *
 * Usage:
 *   import { api } from '@/lib/api-client';
 *   const health = await api.get('/health');
 */

const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3001/api';

class ApiClient {
  private readonly baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl.replace(/\\/$/, '');
  }

  async get<T>(path: string): Promise<T> {
    return this.request<T>('GET', path);
  }

  async post<T>(path: string, body?: unknown): Promise<T> {
    return this.request<T>('POST', path, body);
  }

  async put<T>(path: string, body?: unknown): Promise<T> {
    return this.request<T>('PUT', path, body);
  }

  async delete<T>(path: string): Promise<T> {
    return this.request<T>('DELETE', path);
  }

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const url = \`\${this.baseUrl}\${path}\`;

    const response = await fetch(url, {
      method,
      headers: {
        'Content-Type': 'application/json',
      },
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(
        error.message ?? \`API request failed: \${response.status} \${response.statusText}\`,
      );
    }

    return response.json() as Promise<T>;
  }
}

export const api = new ApiClient(API_BASE_URL);
`;
  }
}
